# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
tasks:
  - init: 'composer create-project laravel/laravel laravel' 

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    visibility: public
    onOpen: open-preview
    

#List the extensions
vscode:
  extensions:
    - felixfbecker.php-debug
